package com.fpt.workflow.ticketcategory.service;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fpt.workflow.definition.domain.WorkflowInputDefinition;import com.fpt.workflow.definition.repository.WorkflowInputDefinitionRepository;
import com.fpt.workflow.form.domain.FormField;import com.fpt.workflow.form.repository.FormFieldRepository;
import com.fpt.workflow.shared.domain.value.*;import com.fpt.workflow.ticketcategory.domain.*;import com.fpt.workflow.ticketcategory.repository.TicketCategoryMappingRepository;
import java.util.*;import org.junit.jupiter.api.Test;
class CategoryMappingServiceTest {
  private final TicketCategoryMappingRepository mappings=mock(TicketCategoryMappingRepository.class);private final WorkflowInputDefinitionRepository inputs=mock(WorkflowInputDefinitionRepository.class);private final FormFieldRepository fields=mock(FormFieldRepository.class);
  private final com.fpt.workflow.ticketcategory.repository.TicketCategoryVersionRepository categoryVersions=mock(com.fpt.workflow.ticketcategory.repository.TicketCategoryVersionRepository.class);
  private final com.fpt.workflow.ticketcategory.repository.TicketCategoryRepository categoryRepo=mock(com.fpt.workflow.ticketcategory.repository.TicketCategoryRepository.class);
  private final UUID categoryVersion=UUID.randomUUID(),workflowVersion=UUID.randomUUID(),formVersion=UUID.randomUUID(),actor=UUID.randomUUID();
  @Test void resolvesFormFieldWithoutUsingSemanticTag(){UUID fieldId=UUID.randomUUID(),targetId=UUID.randomUUID();FormField field=FormField.create(fieldId,formVersion,"purchaseTotal","Total",0,TypeDescriptor.required(CanonicalValueType.NUMBER),false,"unrelated.semantic");WorkflowInputDefinition input=input(targetId,"amount",CanonicalValueType.NUMBER,true,null);stub(input,field,mapping(targetId,MappingSourceType.FORM_FIELD,fieldId,null,null,null));JsonNode result=service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode().put("purchaseTotal",42),actor,"PURCHASE");assertThat(result.path("amount").intValue()).isEqualTo(42);}
  @Test void resolvesAllowlistedSystemContext(){UUID target=UUID.randomUUID();WorkflowInputDefinition input=input(target,"requesterId",CanonicalValueType.USER_ID,true,null);stub(input,null,mapping(target,MappingSourceType.SYSTEM_CONTEXT,null,JsonNodeFactory.instance.textNode("actor.userId"),null,null));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT").path("requesterId").asText()).isEqualTo(actor.toString());}
  @Test void resolvesConstant(){UUID target=UUID.randomUUID();WorkflowInputDefinition input=input(target,"currency",CanonicalValueType.STRING,true,null);stub(input,null,mapping(target,MappingSourceType.CONSTANT,null,null,JsonNodeFactory.instance.textNode("VND"),null));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT").path("currency").asText()).isEqualTo("VND");}
  @Test void evaluatesSafeExpression(){UUID target=UUID.randomUUID(),fieldId=UUID.randomUUID();WorkflowInputDefinition input=input(target,"amount",CanonicalValueType.NUMBER,true,null);FormField field=FormField.create(fieldId,formVersion,"base","Base",0,TypeDescriptor.required(CanonicalValueType.NUMBER),false,null);var expr=JsonNodeFactory.instance.objectNode().put("op","MULTIPLY").set("args",JsonNodeFactory.instance.arrayNode().add(JsonNodeFactory.instance.objectNode().put("path","form.base")).add(2));stub(input,field,mapping(target,MappingSourceType.EXPRESSION,null,expr,null,null));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode().put("base",3),actor,"IT").path("amount").intValue()).isEqualTo(6);}
  @Test void followsExplicitThenWorkflowDefaultOrder(){UUID target=UUID.randomUUID();WorkflowInputDefinition input=input(target,"currency",CanonicalValueType.STRING,true,JsonNodeFactory.instance.textNode("USD"));stub(input,null,mapping(target,MappingSourceType.DEFAULT,null,null,null,JsonNodeFactory.instance.textNode("VND")));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT").path("currency").asText()).isEqualTo("VND");}
  @Test void requiredUnresolvedFails(){UUID target=UUID.randomUUID();when(inputs.findAllByWorkflowVersionIdOrderByOrdinalAsc(workflowVersion)).thenReturn(List.of(input(target,"amount",CanonicalValueType.NUMBER,true,null)));when(mappings.findAllByCategoryVersionIdOrderByOrdinalAsc(categoryVersion)).thenReturn(List.of());when(fields.findAllByFormVersionIdOrderByOrdinalAsc(formVersion)).thenReturn(List.of());assertThatThrownBy(()->service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT")).hasMessageContaining("Required workflow input");}
  @Test void incompatibleValueFails(){UUID target=UUID.randomUUID();WorkflowInputDefinition input=input(target,"amount",CanonicalValueType.NUMBER,true,null);stub(input,null,mapping(target,MappingSourceType.CONSTANT,null,null,JsonNodeFactory.instance.textNode("wrong"),null));assertThatThrownBy(()->service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT")).hasMessageContaining("incompatible");}
  @Test void appliesOrderedStringTransforms(){UUID target=UUID.randomUUID(),fieldId=UUID.randomUUID();WorkflowInputDefinition input=input(target,"name",CanonicalValueType.STRING,true,null);FormField field=FormField.create(fieldId,formVersion,"name","Name",0,TypeDescriptor.required(CanonicalValueType.STRING),false,null);var transforms=JsonNodeFactory.instance.arrayNode().add("TRIM").add("UPPER");stub(input,field,mapping(target,MappingSourceType.FORM_FIELD,fieldId,null,null,null,transforms));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode().put("name"," alice "),actor,"IT").path("name").asText()).isEqualTo("ALICE");}
  @Test void convertsStringToNumberWithAllowlistedTransform(){UUID target=UUID.randomUUID(),fieldId=UUID.randomUUID();WorkflowInputDefinition input=input(target,"amount",CanonicalValueType.NUMBER,true,null);FormField field=FormField.create(fieldId,formVersion,"amountText","Amount",0,TypeDescriptor.required(CanonicalValueType.STRING),false,null);stub(input,field,mapping(target,MappingSourceType.FORM_FIELD,fieldId,null,null,null,JsonNodeFactory.instance.objectNode().put("op","TO_NUMBER")));assertThat(service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode().put("amountText","12.50"),actor,"IT").path("amount").decimalValue()).isEqualByComparingTo("12.50");}
  @Test void rejectsUnsupportedTransform(){UUID target=UUID.randomUUID();WorkflowInputDefinition input=input(target,"name",CanonicalValueType.STRING,true,null);stub(input,null,mapping(target,MappingSourceType.CONSTANT,null,null,JsonNodeFactory.instance.textNode("x"),null,JsonNodeFactory.instance.objectNode().put("op","EVAL")));assertThatThrownBy(()->service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode(),actor,"IT")).hasMessageContaining("Unsupported transform");}
  @Test void formFieldsAreScopedToThePinnedFormVersionNotAllForms(){UUID target=UUID.randomUUID(),otherFormField=UUID.randomUUID();WorkflowInputDefinition input=input(target,"amount",CanonicalValueType.NUMBER,true,null);TicketCategoryMapping mapping=mapping(target,MappingSourceType.FORM_FIELD,otherFormField,null,null,null);when(inputs.findAllByWorkflowVersionIdOrderByOrdinalAsc(workflowVersion)).thenReturn(List.of(input));when(mappings.findAllByCategoryVersionIdOrderByOrdinalAsc(categoryVersion)).thenReturn(List.of(mapping));
    // The mapping source field belongs to a different FormVersion: the query for the pinned
    // form version legitimately returns nothing, so the required input is unresolved rather than
    // silently resolved from another form's field (the old fields.findAll() behavior).
    when(fields.findAllByFormVersionIdOrderByOrdinalAsc(formVersion)).thenReturn(List.of());
    assertThatThrownBy(()->service().resolveInputs(categoryVersion,workflowVersion,formVersion,JsonNodeFactory.instance.objectNode().put("purchaseTotal",42),actor,"IT")).hasMessageContaining("Required workflow input is unresolved: amount");
    verify(fields,never()).findAll();}
  private CategoryMappingService service(){return new CategoryMappingService(mappings,inputs,fields,categoryVersions,categoryRepo);}private WorkflowInputDefinition input(UUID id,String key,CanonicalValueType type,boolean required,JsonNode defaultValue){return WorkflowInputDefinition.create(id,workflowVersion,key,"different.semantic",TypeDescriptor.required(type),required,defaultValue,null,false,null,0);}private TicketCategoryMapping mapping(UUID target,MappingSourceType type,UUID field,JsonNode expression,JsonNode constant,JsonNode defaultValue){return mapping(target,type,field,expression,constant,defaultValue,null);}private TicketCategoryMapping mapping(UUID target,MappingSourceType type,UUID field,JsonNode expression,JsonNode constant,JsonNode defaultValue,JsonNode transform){return TicketCategoryMapping.create(UUID.randomUUID(),categoryVersion,target,type,field,expression,constant,defaultValue,"ERROR",transform,0);}private void stub(WorkflowInputDefinition input,FormField field,TicketCategoryMapping mapping){when(inputs.findAllByWorkflowVersionIdOrderByOrdinalAsc(workflowVersion)).thenReturn(List.of(input));when(mappings.findAllByCategoryVersionIdOrderByOrdinalAsc(categoryVersion)).thenReturn(List.of(mapping));when(fields.findAllByFormVersionIdOrderByOrdinalAsc(formVersion)).thenReturn(field==null?List.of():List.of(field));}
}
