package com.fpt.workflow.ticket.service;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fpt.workflow.definition.domain.WorkflowStateDefinition;import com.fpt.workflow.definition.repository.WorkflowStateDefinitionRepository;
import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.jdbc.core.JdbcTemplate;
class BusinessStateServiceTest {
  @Test void closesPreviousStateUpdatesCacheAndAppendsHistory(){JdbcTemplate jdbc=mock(JdbcTemplate.class);WorkflowStateDefinitionRepository states=mock(WorkflowStateDefinitionRepository.class);UUID workflow=UUID.randomUUID(),ticket=UUID.randomUUID(),event=UUID.randomUUID();when(states.findAllByWorkflowVersionIdOrderByDisplayOrderAsc(workflow)).thenReturn(List.of(WorkflowStateDefinition.create(UUID.randomUUID(),workflow,"WAITING_FINANCE","Waiting for Finance",null,null,false,1,JsonNodeFactory.instance.objectNode())));when(jdbc.update(startsWith("UPDATE tickets"),any(Object[].class))).thenReturn(1);var service=new BusinessStateService(jdbc,states,UUID::randomUUID,()->Instant.parse("2026-09-14T00:00:00Z"),new ObjectMapper());service.transition(ticket,event,workflow,"WAITING_FINANCE",null,JsonNodeFactory.instance.objectNode());verify(jdbc).update(startsWith("UPDATE ticket_state_history"),any(Object[].class));verify(jdbc).update(startsWith("UPDATE tickets"),any(Object[].class));verify(jdbc).update(startsWith("INSERT INTO ticket_state_history"),any(Object[].class));}
  @Test void rejectsUndeclaredBusinessState(){JdbcTemplate jdbc=mock(JdbcTemplate.class);WorkflowStateDefinitionRepository states=mock(WorkflowStateDefinitionRepository.class);UUID workflow=UUID.randomUUID();when(states.findAllByWorkflowVersionIdOrderByDisplayOrderAsc(workflow)).thenReturn(List.of());var service=new BusinessStateService(jdbc,states,UUID::randomUUID,Instant::now,new ObjectMapper());assertThatThrownBy(()->service.transition(UUID.randomUUID(),UUID.randomUUID(),workflow,"UNKNOWN",null,null)).hasMessageContaining("WORKFLOW_STATE_NOT_DECLARED");verifyNoInteractions(jdbc);}
}
