spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
      connection-timeout: 10000
      keepalive-time: 120000
      initialization-fail-timeout: 1
      max-lifetime: 1500000
      maximum-pool-size: 4
      minimum-idle: 0
      pool-name: WorkflowPlatformTestPool
      validation-timeout: 5000

platform:
  outbox:
    publisher:
      enabled: false
  jobs:
    worker:
      enabled: false
  sla:
    poller:
      enabled: false
  security:
    dev-headers:
      enabled: true
