package com.fpt.workflow.definition.validation;

public enum ValidationStage {
  DEFINITION_SCHEMA,
  NODE_CONFIG,
  REFERENCE_PATH_TYPE,
  GRAPH_STRUCTURE,
  NODE_SEMANTICS,
  ROUTING,
  PARTICIPANT_TASK,
  MULTI_INSTANCE,
  PARALLEL_JOIN_TOKEN_SCOPE,
  REWORK,
  FORM_VARIABLE,
  SLA_CALENDAR,
  INTEGRATION_CONNECTOR,
  SUBWORKFLOW,
  PERMISSION_SECURITY,
  VERSION_REVISION,
  CROSS_NODE_EXECUTION
}
